### ISSUE TITLE
How to code in C++ instead of JS ?

### ISSUE THREAD

**Issue by adrien-thierry** [tido64/rainbow#535]
Hi @tido64 

Where can we write code in c++ instead of using Ducktape in JS ?

Before integrating NectarJS, we could integrate NectarCPP to write in JS like syntax in cpp

thx

**Comment by adrien-thierry** [comment]
To be more precise, i'm asking this to start to integrate https://github.com/nectar-lang/NectarCPP before integrating NectarJS

**Comment by tido64** [comment]
There is some documentation here: https://nguyen.works/rainbow/docs/basics/

IMO, the C++ API should stay idiomatic C++. If someone wants JS-ish syntax in C++, that's something they can add for themselves. I'm also wary against integrating anything GPL-licensed as this repo is licensed under MIT.

**Comment by adrien-thierry** [comment]
The point is to start to integrate Rainbow as a module for NectarCPP/NectarJS
